import { loadPlugins } from '../helpers/plugin.js';
import { handle } from './command-hoc.js';
import { program } from './program.js';
import type { Adapter } from '../adapters/adapter.js';
import { SYMBOLS } from '../symbols.js';

const DEFAULT_STALE_MINUTES = '10';

export default async () => {
    const command = program
        .command('cleanup')
        .description('Return tests left claimed by an interrupted shard to the queue.');

    for await (const { register, subCommand } of loadPlugins(command)) {
        const storage = subCommand.name();
        subCommand
            .requiredOption('--run-id <string>', 'Run id generated by create command')
            .option(
                '--stale-minutes <number>',
                'How long a test may stay claimed before it counts as abandoned. Must exceed the duration of the longest single test, otherwise a test that is still running will be handed to another shard. Use 0 only once every shard has exited.',
                DEFAULT_STALE_MINUTES,
            )
            .action(
                handle(async (container, options) => {
                    const staleMinutes = Number(options.staleMinutes);
                    if (!Number.isFinite(staleMinutes) || staleMinutes < 0) {
                        throw new Error('--stale-minutes must be a non-negative number');
                    }
                    await register(container, options);
                    const adapter = container.get<Adapter>(SYMBOLS.Adapter);
                    if (!adapter.cleanupStaleTests) {
                        console.log(
                            `Cleanup is not supported for ${storage} storage: claiming a test removes it from the queue, so there is no record left to reset.`,
                        );
                        return;
                    }
                    const count = await adapter.cleanupStaleTests(options.runId, staleMinutes);
                    console.log(`Returned ${count} stale test(s) to the queue`);
                }),
            );
    }
};
